### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by NirantK** [Hasil-Sharma/remote-work-setup#1]
Remote work setup script incomplete. 

Datasets and assignments download missing
Sleep is missing. 

@Hasil-Sharma assign to self, please?

**Comment by Hasil-Sharma** [comment]
Hahaha. 

You need to stop stalking me on GitHub :sweat_smile:

**Comment by Hasil-Sharma** [comment]
Hahaha. 

This is enough to get me started from any public computer (with big screen :smile: ).
